import { USER_ROLES } from "./roles.js";

export const PERMISSIONS = Object.freeze({
  VIEW_GLOBAL_DASHBOARD: "view_global_dashboard",
  MANAGE_ESTABLISHMENTS: "manage_establishments",
  MANAGE_PLANS: "manage_plans",
  MANAGE_SUBSCRIPTIONS: "manage_subscriptions",
  VIEW_PAYMENTS: "view_payments",
  MANAGE_USERS: "manage_users",

  MANAGE_PRODUCTS: "manage_products",
  MANAGE_CATEGORIES: "manage_categories",
  MANAGE_TABLES: "manage_tables",
  MANAGE_EMPLOYEES: "manage_employees",

  VIEW_ORDERS: "view_orders",
  CREATE_ORDERS: "create_orders",
  UPDATE_ORDER_STATUS: "update_order_status",
  CLOSE_ORDERS: "close_orders",
});

export const ROLE_PERMISSIONS = Object.freeze({
  [USER_ROLES.SUPER_ADMIN]: [
    PERMISSIONS.VIEW_GLOBAL_DASHBOARD,
    PERMISSIONS.MANAGE_ESTABLISHMENTS,
    PERMISSIONS.MANAGE_PLANS,
    PERMISSIONS.MANAGE_SUBSCRIPTIONS,
    PERMISSIONS.VIEW_PAYMENTS,
    PERMISSIONS.MANAGE_USERS,
  ],

  [USER_ROLES.SUBSCRIBER]: [
    PERMISSIONS.MANAGE_PRODUCTS,
    PERMISSIONS.MANAGE_CATEGORIES,
    PERMISSIONS.MANAGE_TABLES,
    PERMISSIONS.MANAGE_EMPLOYEES,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.CREATE_ORDERS,
    PERMISSIONS.UPDATE_ORDER_STATUS,
    PERMISSIONS.CLOSE_ORDERS,
  ],

  [USER_ROLES.MANAGER]: [
    PERMISSIONS.MANAGE_PRODUCTS,
    PERMISSIONS.MANAGE_CATEGORIES,
    PERMISSIONS.MANAGE_TABLES,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.CREATE_ORDERS,
    PERMISSIONS.UPDATE_ORDER_STATUS,
    PERMISSIONS.CLOSE_ORDERS,
  ],

  [USER_ROLES.EMPLOYEE]: [
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.UPDATE_ORDER_STATUS,
  ],

  [USER_ROLES.WAITER]: [
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.CREATE_ORDERS,
    PERMISSIONS.UPDATE_ORDER_STATUS,
    PERMISSIONS.CLOSE_ORDERS,
  ],

  [USER_ROLES.KITCHEN]: [
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.UPDATE_ORDER_STATUS,
  ],
});