import {
  PERMISSIONS,
} from "./permissions.js";

import {
  USER_ROLES,
} from "./roles.js";

export const ROLE_PERMISSIONS =
  Object.freeze({
    [USER_ROLES.SUPER_ADMIN]: [
      PERMISSIONS.VIEW_GLOBAL_DASHBOARD,
      PERMISSIONS.MANAGE_ESTABLISHMENTS,
      PERMISSIONS.MANAGE_USERS,
      PERMISSIONS.MANAGE_PLANS,
      PERMISSIONS.MANAGE_SUBSCRIPTIONS,
      PERMISSIONS.VIEW_PAYMENTS,
      PERMISSIONS.VIEW_AUDIT_LOGS,
    ],

    [USER_ROLES.SUBSCRIBER]: [
      PERMISSIONS.MANAGE_PRODUCTS,
      PERMISSIONS.MANAGE_CATEGORIES,
      PERMISSIONS.MANAGE_TABLES,
      PERMISSIONS.MANAGE_EMPLOYEES,
      PERMISSIONS.MANAGE_ESTABLISHMENT_SETTINGS,

      PERMISSIONS.VIEW_ORDERS,
      PERMISSIONS.CREATE_ORDERS,
      PERMISSIONS.UPDATE_ORDER_STATUS,
      PERMISSIONS.CLOSE_ORDERS,
      PERMISSIONS.CANCEL_ORDERS,

      PERMISSIONS.VIEW_SERVICE_CALLS,
      PERMISSIONS.MANAGE_SERVICE_CALLS,
    ],

    [USER_ROLES.MANAGER]: [
      PERMISSIONS.MANAGE_PRODUCTS,
      PERMISSIONS.MANAGE_CATEGORIES,
      PERMISSIONS.MANAGE_TABLES,

      PERMISSIONS.VIEW_ORDERS,
      PERMISSIONS.CREATE_ORDERS,
      PERMISSIONS.UPDATE_ORDER_STATUS,
      PERMISSIONS.CLOSE_ORDERS,
      PERMISSIONS.CANCEL_ORDERS,

      PERMISSIONS.VIEW_SERVICE_CALLS,
      PERMISSIONS.MANAGE_SERVICE_CALLS,
    ],

    [USER_ROLES.EMPLOYEE]: [
      PERMISSIONS.VIEW_ORDERS,
      PERMISSIONS.UPDATE_ORDER_STATUS,

      PERMISSIONS.VIEW_SERVICE_CALLS,
      PERMISSIONS.MANAGE_SERVICE_CALLS,
    ],

    [USER_ROLES.WAITER]: [
      PERMISSIONS.VIEW_ORDERS,
      PERMISSIONS.CREATE_ORDERS,
      PERMISSIONS.UPDATE_ORDER_STATUS,
      PERMISSIONS.CLOSE_ORDERS,

      PERMISSIONS.VIEW_SERVICE_CALLS,
      PERMISSIONS.MANAGE_SERVICE_CALLS,
    ],

    [USER_ROLES.KITCHEN]: [
      PERMISSIONS.VIEW_ORDERS,
      PERMISSIONS.UPDATE_ORDER_STATUS,
    ],
  });