export const menuCategories = [
  {
    id: "bebidas",
    nome: "Bebidas",
    icone: "🥤",
    descricao: "Sucos, refrigerantes e drinks",
    ordem: 1,
    ativa: true,
  },
  {
    id: "porcoes",
    nome: "Porções",
    icone: "🍟",
    descricao: "Petiscos e entradas para compartilhar",
    ordem: 2,
    ativa: true,
  },
  {
    id: "lanches",
    nome: "Lanches",
    icone: "🍔",
    descricao: "Hambúrgueres e sanduíches artesanais",
    ordem: 3,
    ativa: true,
  },
  {
    id: "sobremesas",
    nome: "Sobremesas",
    icone: "🍰",
    descricao: "Doces e sobremesas irresistíveis",
    ordem: 4,
    ativa: true,
  },
];

export const menuItems = [
  {
    id: 1,
    nome: "Coca-Cola",
    preco: 8.5,
    descricao: "Lata 350ml gelada",
    categoria: "bebidas",
    emoji: "🥤",
  },
  {
    id: 2,
    nome: "Suco Natural",
    preco: 14,
    descricao: "Laranja, limão ou maracujá - 500ml",
    categoria: "bebidas",
    emoji: "🍊",
  },
  {
    id: 3,
    nome: "Heineken",
    preco: 16,
    descricao: "Long neck 330ml bem gelada",
    categoria: "bebidas",
    emoji: "🍺",
  },
  {
    id: 4,
    nome: "Água Mineral",
    preco: 5,
    descricao: "Com ou sem gás 500ml",
    categoria: "bebidas",
    emoji: "💧",
  },
  {
    id: 5,
    nome: "Caipirinha",
    preco: 25,
    descricao: "Cachaça artesanal, limão e açúcar",
    categoria: "bebidas",
    emoji: "🍹",
  },
  {
    id: 6,
    nome: "Milk Shake",
    preco: 22,
    descricao: "Chocolate, baunilha ou morango - 400ml",
    categoria: "bebidas",
    emoji: "🥛",
  },
  {
    id: 7,
    nome: "Batata Frita",
    preco: 28,
    descricao: "Porção 300g com molho especial da casa",
    categoria: "porcoes",
    emoji: "🍟",
  },
  {
    id: 8,
    nome: "Frango Frito",
    preco: 45,
    descricao: "Porção 400g temperado e crocante",
    categoria: "porcoes",
    emoji: "🍗",
  },
  {
    id: 9,
    nome: "Onion Rings",
    preco: 32,
    descricao: "Anéis de cebola empanados - 8 unid.",
    categoria: "porcoes",
    emoji: "🧅",
  },
  {
    id: 10,
    nome: "Bolinha de Queijo",
    preco: 35,
    descricao: "12 unid. com cream cheese e molho",
    categoria: "porcoes",
    emoji: "🧀",
  },
  {
    id: 11,
    nome: "Mix Petiscos",
    preco: 58,
    descricao: "Batata, anel e frango - serve 2 a 4",
    categoria: "porcoes",
    emoji: "🍽️",
  },
  {
    id: 12,
    nome: "X-Burguer Clássico",
    preco: 32,
    descricao: "Blend 180g, queijo prato, alface e tomate",
    categoria: "lanches",
    emoji: "🍔",
  },
  {
    id: 13,
    nome: "X-Bacon Duplo",
    preco: 42,
    descricao: "Blend 2x180g, bacon e queijo cheddar",
    categoria: "lanches",
    emoji: "🥓",
  },
  {
    id: 14,
    nome: "Smash Burger",
    preco: 38,
    descricao: "Blend smash 150g, molho especial e cheddar",
    categoria: "lanches",
    emoji: "💥",
  },
  {
    id: 15,
    nome: "Veggie Burger",
    preco: 36,
    descricao: "Blend grão-de-bico, rúcula e pesto",
    categoria: "lanches",
    emoji: "🥗",
  },
  {
    id: 16,
    nome: "Hot Dog Gourmet",
    preco: 28,
    descricao: "Salsicha artesanal com cremes especiais",
    categoria: "lanches",
    emoji: "🌭",
  },
  {
    id: 17,
    nome: "Pudim Tradicional",
    preco: 18,
    descricao: "Pudim de leite condensado com calda",
    categoria: "sobremesas",
    emoji: "🍮",
  },
  {
    id: 18,
    nome: "Brownie + Sorvete",
    preco: 26,
    descricao: "Brownie quentinho com bola de creme",
    categoria: "sobremesas",
    emoji: "🍫",
  },
  {
    id: 19,
    nome: "Açaí 500ml",
    preco: 38,
    descricao: "Açaí cremoso com granola e frutas",
    categoria: "sobremesas",
    emoji: "🫐",
  },
  {
    id: 20,
    nome: "Cheesecake",
    preco: 28,
    descricao: "Nova York com calda de frutas vermelhas",
    categoria: "sobremesas",
    emoji: "🍰",
  },
  {
    id: 21,
    nome: "Petit Gateau",
    preco: 32,
    descricao: "Chocolate vulcão com sorvete de baunilha",
    categoria: "sobremesas",
    emoji: "🎂",
  },
];
