export const menuCategories = [
  {
    id: "bebidas",
    nome: "Bebidas",
    icone: "🥤",
    descricao: "Sucos, refrigerantes e drinks",
  },
  {
    id: "porcoes",
    nome: "Porcoes",
    icone: "🍟",
    descricao: "Petiscos e entradas para compartilhar",
  },
  {
    id: "lanches",
    nome: "Lanches",
    icone: "🍔",
    descricao: "Hamburgueres e sanduiches artesanais",
  },
  {
    id: "sobremesas",
    nome: "Sobremesas",
    icone: "🍰",
    descricao: "Doces e sobremesas irresistiveis",
  },
];

export const menuItems = [
  {
    id: 1,
    nome: "Coca-Cola",
    preco: 8.5,
    descricao: "Lata 350ml gelada",
    categoria: "bebidas",
    emoji: "🥤",
  },
  {
    id: 2,
    nome: "Suco Natural",
    preco: 14,
    descricao: "Laranja, limao ou maracuja - 500ml",
    categoria: "bebidas",
    emoji: "🍊",
  },
  {
    id: 3,
    nome: "Heineken",
    preco: 16,
    descricao: "Long neck 330ml bem gelada",
    categoria: "bebidas",
    emoji: "🍺",
  },
  {
    id: 4,
    nome: "Batata Frita",
    preco: 28,
    descricao: "Porcao 300g com molho especial da casa",
    categoria: "porcoes",
    emoji: "🍟",
  },
  {
    id: 5,
    nome: "Frango Frito",
    preco: 45,
    descricao: "Porcao 400g temperado e crocante",
    categoria: "porcoes",
    emoji: "🍗",
  },
  {
    id: 6,
    nome: "X-Burguer Classico",
    preco: 32,
    descricao: "Blend 180g, queijo prato, alface e tomate",
    categoria: "lanches",
    emoji: "🍔",
  },
  {
    id: 7,
    nome: "X-Bacon Duplo",
    preco: 42,
    descricao: "Blend 2x180g, bacon e queijo cheddar",
    categoria: "lanches",
    emoji: "🥓",
  },
  {
    id: 8,
    nome: "Pudim Tradicional",
    preco: 18,
    descricao: "Pudim de leite condensado com calda",
    categoria: "sobremesas",
    emoji: "🍮",
  },
  {
    id: 9,
    nome: "Brownie + Sorvete",
    preco: 26,
    descricao: "Brownie quentinho com bola de creme",
    categoria: "sobremesas",
    emoji: "🍫",
  },
];
